### PR TITLE
db-436/risk low/tweaks-to-homepage

### PR DESCRIPTION
**Pull request by kathanner**

### CODE REVIEW

**Comment by kathanner** [comment]
@mhigbyflowers -- updated homepage text (I think)

**Comment by kathanner** [comment]
@mhigbyflowers -- attempt to add icons on homepage (could not load the site locally)

**Review by mhigbyflowers — CHANGES_REQUESTED** [review]
the search-bar is now smaller on all pages. 
is this what was requested? 
If so great!
If not can you add the changes to #db-search-bar to: public-ui/src/app/views/quick-search/quick-search.component.css
It will override the style just on the home page.

**Comment by kathanner** [comment]
@mhigbyflowers the CSS update is in. Can you review again please?

**Review by mhigbyflowers — APPROVED** [review]
:+1:

**Pull request merged**
