### PR TITLE
[Db-1278][risk:no]Infinite scroll on EHR

### PR DESCRIPTION
**Pull request by mhigbyflowers**

### CODE REVIEW

**Comment by SrushtiGangireddy** [comment]
image

image

The count on the top keeps showing some random results number i guess its the number of results fetched but its sometimes > the number of rows available.

**Comment by mhigbyflowers** [comment]
> image
> 
> image
> 
> The count on the top keeps showing some random results number i guess its the number of results fetched but its sometimes > the number of rows available.

I removed the "showing top #" cause we are now showing all results
image

**Comment by SrushtiGangireddy** [comment]
Looks good, overall. Could we add a loader at the bottom when the results are waiting to load ?
image

During search, the top 10 concepts and the concept count is right but the results are not taking the search word into account i think. Its displaying all the results. 
image

**Comment by SrushtiGangireddy** [comment]
I was getting this when i searched with "lab" on labs and measurements. 
image

**Comment by SrushtiGangireddy** [comment]
Also, when i search with "syndrome" in conditions, the count on says 873 concepts but after 50 it does not load anymore. 
image

**Review by SrushtiGangireddy — APPROVED** [review]
Looks good to me. Thanks.

**Pull request merged**
