### PR TITLE
[risk=no] [RW-6140] Adding COPE sections

### PR DESCRIPTION
**Pull request by SrushtiGangireddy**
1. Added cope sections in data.
2. Modified api to accommodate sections.

### CODE REVIEW

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
image

**Review by mhigbyflowers — APPROVED** [review]
👍  look great, Thanks!

**Pull request merged**
