### PR TITLE
[risk=no] [DB-1043] Add sorting on gene, allele count, allele number, allele frequency

### PR DESCRIPTION
**Pull request by SrushtiGangireddy**
image

### CODE REVIEW

**Comment by mhigbyflowers** [comment]
I am not able to get any column to sort except for Variant.
When I click to sort gene, shouldn't the arrow disappear on Variant?
Maybe there should be a small icon button next to the column that indicates that the column can be sorted.

**Comment by SrushtiGangireddy** [comment]
@mhigbyflowers  So, i was using local api. You should be able to use local api to see sorting on gene, allele count and frequency.

**Comment by SrushtiGangireddy** [comment]
> I am not able to get any column to sort except for Variant. When I click to sort gene, shouldn't the arrow disappear on Variant? Maybe there should be a small icon button next to the column that indicates that the column can be sorted.

When we click on gene sort, the arrow on variant id would change back to the original asc arrow (which is. default).

**Comment by SrushtiGangireddy** [comment]
@mhigbyflowers Let me know if you can get the local api running or i can separate out api part into another ticket.

**Comment by mhigbyflowers** [comment]
@SrushtiGangireddy  OK, I am able it get it to work.
I think there should not be an arrow on any columns unless it is being sorted.

**Comment by SrushtiGangireddy** [comment]
> @SrushtiGangireddy OK, I am able it get it to work. I think there should not be an arrow on any columns unless it is being sorted.

We should then probably think about a different icon or way to let user know that column is sortable. i was thinking we could have the arrow on the column and then have it big when the sort is active. Let me knw what you think.

**Pull request closed without merging**
