### PR TITLE
[risk=no] [DB-684] Generate data needed for percentage graphs 

### PR DESCRIPTION
**Pull request by SrushtiGangireddy**
1. generate data needed for percentage graphs

### CODE REVIEW

**Review by mhigbyflowers — COMMENTED** [review]
When first opening the charts Percernate is selected but the y-axis shows counts.
Also, the y-axis label should be "Participant Percentage"

image

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
image

**Review by mhigbyflowers — APPROVED** [review]
Looks good 👍  thanks

**Pull request merged**
