### PR TITLE
[risk=no] Measurement filter fix

### PR DESCRIPTION
**Pull request by SrushtiGangireddy**
Measurement filter does not work once the row is expanded.
Fixing it by adding filter on each checkboxclick.

### CODE REVIEW

**Comment by SrushtiGangireddy** [comment]
image
Before

**Comment by SrushtiGangireddy** [comment]
image
Before

**Comment by SrushtiGangireddy** [comment]
image
Now

**Review by mhigbyflowers — APPROVED** [review]
looks good 👍

**Pull request merged**
