### PR TITLE
[risk=no] [DB-917] Top nav and footer changes for beta launch

### PR DESCRIPTION
**Pull request by SrushtiGangireddy**
Changing top nav and footer to match research hub. 
https://docs.google.com/presentation/d/1Qi023lA2qaB6VJFnuOoa-CjBvVuwxAQlxlIkO9W_eV8/edit#slide=id.g6ebbd3d096_0_0
Conditioning these changes on feature flag so that they wont be pushed till launch.

### CODE REVIEW

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
image

**Review by dolbeew — APPROVED** [review]
LGTM

**Comment by SrushtiGangireddy** [comment]
Thanks.

**Pull request merged**
