### PR TITLE
[risk=no] [DB-892] Font sizes update

### PR DESCRIPTION
**Pull request by SrushtiGangireddy**
try making the smallest to a size 14 (graph labels, tooltips). the rest to a size 18

See if we can update tooltips' color to be white with dark purple font. Might need a shadow to make it pop off the page? Try the shadow like on the homepage tiles. Let’s try font size 18, maybe 14.

### CODE REVIEW

**Review by mhigbyflowers — COMMENTED** [review]
image
This tooltip is missing

**Review by mhigbyflowers — CHANGES_REQUESTED** [review]
image
This tooltip is missing

The font changes on the percent and count look good. I think we should push those changes and wait to push the tooltip background changes.

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
image

**Comment by SrushtiGangireddy** [comment]
Looks okay to me. It needs local data migrations runs may be.
(since we changed survey name from healthcare to "health care")

**Review by mhigbyflowers — APPROVED** [review]
thanks for fixing. 👍 
I think the black tool-tip looks better, but I know 508 says it is more assessable.  Lets merge it in to test and see what Hellen thinks.

**Comment by SrushtiGangireddy** [comment]
Yes, i was just going by ticket. Let us see. We can revert back from test.

**Pull request merged**
